services:  
  # Microservicio de Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      # Variables de entorno de Next.js
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: production
      # Variables de Mailtrap desde archivo .env
      # SECURITY WARNING: Ensure MAILTRAP credentials are set in environment
      MAILTRAP_USER: ${MAILTRAP_USER}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
      MAILTRAP_FROM_EMAIL: ${MAILTRAP_FROM_EMAIL:-noreply@unica.edu.pe}
      # URLs base para desarrollo
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    env_file:
      - ./frontend/.env
    depends_on:
      autenticacion:
        condition: service_healthy
      intranet:
        condition: service_healthy
      matricula:
        condition: service_healthy
    networks:
      - escuela-network
    restart: unless-stopped

  # Microservicio de Autenticación
  autenticacion:
    build: ./backend/Autenticacion
    ports:
      - "8080:8080"
    environment:
      # SECURITY WARNING: Use strong database credentials in production
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/autenticacion
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SPRING_PROFILES_ACTIVE: docker
      # SECURITY WARNING: JWT_SECRET must be set with a strong value
      JWT_SECRET: ${JWT_SECRET}
      # Google OAuth credentials - required for OAuth functionality
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - escuela-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  # Microservicio de Intranet
  intranet:
    build: ./backend/Intranet
    ports:
      - "8081:8081"
    environment:
      # SECURITY WARNING: Use strong database credentials in production
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/intranet
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SPRING_PROFILES_ACTIVE: docker
      # SECURITY WARNING: JWT_SECRET must be set with a strong value
      JWT_SECRET: ${JWT_SECRET}
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - escuela-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  # Microservicio de Matrícula
  matricula:
    build: ./backend/Matricula
    ports:
      - "8082:8082"
    environment:
      # SECURITY WARNING: Use strong database credentials in production
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/matricula
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SPRING_PROFILES_ACTIVE: docker
      # SECURITY WARNING: JWT_SECRET must be set with a strong value
      JWT_SECRET: ${JWT_SECRET}
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - escuela-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  # Servicio de Base de Datos
  db:
    image: postgres:17.5
    environment:
      # SECURITY WARNING: Use strong credentials in production
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - escuela-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Servicio de pgAdmin para administrar las bases de datos
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      # SECURITY WARNING: Change these default credentials in production
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@unica.edu.pe}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-change_this_password_in_production}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8079:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - escuela-network

volumes:
  pgdata:
  pgadmin-data:

networks:
  escuela-network:
    driver: bridge
