import { NavItem } from "./Nav";
import {
  ButtonProps,
  ButtonAsButton,
  ButtonAsLink,
  BaseButtonProps,
} from "./Button";
import { CarouselSlide, CarouselProps } from "./Carrousel";
import {
  Role,
  LoginRequest,
  AuthResponse,
  MessageResponse,
  UsuarioResponse,
  AuthContextType,
  ApiError,
} from "./auth";
import { SidebarProps, SidebarItemProps } from "./Sidebar";
import {
  Authority,
  AuthorityCardProps,
  AuthorityGridProps,
  AuthorityPageHeaderProps,
} from "./authority";
import {
  ContactInfo,
  DirectoryEntry,
  DirectorySection,
  ContactFormData,
  ContactFormProps,
  ContactInfoCardProps,
  DirectoryTableProps,
  DirectoryMenuProps,
  MapProps,
} from "./contact";
import {
  Doctorado,
  Programa,
  CategoriaAcademica,
  HeroSectionProps,
  SectionHeaderProps,
  DoctoradoCardProps,
  DoctoradosGridProps,
  ProgramaItemProps,
  MaestriaCategoriaProps,
  MaestriasGridProps,
} from "./programs";

export type {
  NavItem,
  ButtonProps,
  ButtonAsButton,
  ButtonAsLink,
  BaseButtonProps,
  CarouselSlide,
  CarouselProps,
  Role,
  LoginRequest,
  AuthResponse,
  MessageResponse,
  UsuarioResponse,
  AuthContextType,
  ApiError,
  SidebarProps,
  SidebarItemProps,
  Authority,
  AuthorityCardProps,
  AuthorityGridProps,
  AuthorityPageHeaderProps,
  ContactInfo,
  DirectoryEntry,
  DirectorySection,
  ContactFormData,
  ContactFormProps,
  ContactInfoCardProps,
  DirectoryTableProps,
  DirectoryMenuProps,
  MapProps,
  Doctorado,
  Programa,
  CategoriaAcademica,
  HeroSectionProps,
  SectionHeaderProps,
  DoctoradoCardProps,
  DoctoradosGridProps,
  ProgramaItemProps,
  MaestriaCategoriaProps,
  MaestriasGridProps,
};
